name = "test-mail-fetcher"
compatibility_date = "2024-06-01"
workers_dev = false

[triggers]
crons = ["*/12 * * * *"]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV"
id = "64283b43b1924bcea2821f902f7e938b"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
